# Generated by Django 4.2.2 on 2025-02-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(
                help_text='Enter a book genre (e.g. Science Fiction, French...)', max_length=200, unique=True),
        ),
    ]
