# Generated by Django 4.2.2 on 2025-02-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    help_text='Enter a language name', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='MyModelName',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
