# Generated by Django 4.2.2 on 2025-02-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_language_delete_mymodelname_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_birth',
            new_name='birth',
        ),
    ]
